### ISSUE TITLE
Define the home page

### ISSUE THREAD

**Issue by benmatselby** [somedevsdo/blog#5]
Homepage designs can be found here: https://www.figma.com/file/Oc9v5LR4SPwwaQyijhEXnR/Website?node-id=26%3A29

3 sizes in two colour themes.

![image](https://user-images.githubusercontent.com/20924669/123748494-35971380-d8ac-11eb-84a4-78a0b8357553.png)

**Comment by andrewbarnesweb** [comment]
My thoughts in the short term, to get us up and running, is for the homepage to just be the blog feed... Gets us away from having to think about how we start position the group at this stage, and can focus on building up content and features.

![image](https://user-images.githubusercontent.com/20924669/118613963-2a35d000-b7b7-11eb-9668-e757f838e9fb.png)

I guess that bleeds into #6 too. Since that would be an overhead also.

**Comment by andrewbarnesweb** [comment]
I think it's probably worthwhile blocking this for now, while we focus on getting posts up and running and linking to author pages.

**Comment by andrewbarnesweb** [comment]
Something like this will do for now. 

_I'll try and get a mobile and dark mode view before the weekend is out._

- I've offset the image on the homepage to the right, and added a dark fill that blends into the picture.
- We can worry about how many cards to show when we get to a lot of content. But not really something to worry about today.
- Logo is still being worked on (I think... @davidn0rman ?)
- We'll hack a basic footer in at some point!

<img width="1441" alt="Home@2x" src="https://user-images.githubusercontent.com/20924669/120063650-2aa85380-c060-11eb-94db-fb5add11567c.png">

**Comment by davidn0rman** [comment]
We still open to Font changes? Was playing around with some the other day but didn't get far for work work! Not sure why but the heading font isn't gelling with me. But not a blocker!

As for logo, I've done some more ideas the other day but again, work. I'll try and put some more down and share later when the boy is napping. 😎

**Comment by andrewbarnesweb** [comment]
Deffo! I think it'll all change since neither of us have had enough time to go at the designs properly. So we can start somewhere and finesse 👍🏽. 

I think the beauty at this stage is that the site is so light (only 2-3 pages) that a complete redesign won't take much doing since the real effort is hooking up all the content and getting it linking etc.

**Comment by andrewbarnesweb** [comment]
(As long as you don't full caps lock on us 😁)

**Comment by davidn0rman** [comment]
> (As long as you don't full caps lock on us 😁)

![rainn-wilson.gif](https://user-images.githubusercontent.com/20046480/120067353-fbe7a880-c072-11eb-8017-e31317b80011.gif)

**Comment by andrewbarnesweb** [comment]
- https://www.figma.com/file/Oc9v5LR4SPwwaQyijhEXnR/blog?node-id=118%3A157
- https://www.figma.com/file/Oc9v5LR4SPwwaQyijhEXnR/blog?node-id=110%3A109
- https://www.figma.com/file/Oc9v5LR4SPwwaQyijhEXnR/blog?node-id=118%3A482
- https://www.figma.com/file/Oc9v5LR4SPwwaQyijhEXnR/blog?node-id=118%3A576

# Large dark

<img width="1441" alt="Home" src="https://user-images.githubusercontent.com/20924669/120069225-aca67580-c07c-11eb-8d8b-9ea904f8b57e.png">

# Large light

<img width="1441" alt="Home@2x" src="https://user-images.githubusercontent.com/20924669/120069213-9993a580-c07c-11eb-9143-6640d12493ca.png">

# Small dark

<img width="375" alt="Frame 1 (1)" src="https://user-images.githubusercontent.com/20924669/120069248-ca73da80-c07c-11eb-8397-bbca83907e10.png">

# Small light

<img width="375" alt="Frame 2 (1)" src="https://user-images.githubusercontent.com/20924669/120069233-bcbe5500-c07c-11eb-8a0c-2896a39b8725.png">

**Comment by andrewbarnesweb** [comment]
Removed the blocked label, since there's enough to go at for now.

**Comment by andrewbarnesweb** [comment]
Updated description with newer design.
